// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqfPeknHQbsJRQyaA5oZCae5iDWkmqhpU',
    appId: '1:294662201113:android:0e0076287a9b941506af88',
    messagingSenderId: '294662201113',
    projectId: 'eodaego-6e6fe',
    storageBucket: 'eodaego-6e6fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVA41XeZWYZ9qhIBJv86zNpIEl1T7qeWk',
    appId: '1:294662201113:ios:15b16e17ea2625f806af88',
    messagingSenderId: '294662201113',
    projectId: 'eodaego-6e6fe',
    storageBucket: 'eodaego-6e6fe.firebasestorage.app',
    iosClientId:
        '294662201113-rnr5lb8hqt71cr7ovdjjcjedj2jtnv8e.apps.googleusercontent.com',
    iosBundleId: 'com.elipair.eodaego',
  );
}
